version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets
      - ./conf.json:/app/conf.json
    command: ["node", "index.js"]
