version: "3.8"
services:
  discord-bot:
    build:
      context: .
    volumes:
      - C:/Users/damie/OneDrive/Bureau/Projets/Botdiscord:/app  # Lier le dossier local au conteneur
    ports:
      - "3000:3000"  # Si ton bot écoute sur un port
    environment:
      - NODE_ENV=development
    command: node index.js  # Commande pour démarrer le bot
    restart: unless-stopped  # Redémarrer le conteneur sauf si arrêté manuellement